// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aF60c3G3czH6ZJCI9hY37gmu-72IgG8',
    appId: '1:154524726030:web:aa1b8b93fae82a188add5f',
    messagingSenderId: '154524726030',
    projectId: 'flutter-insta-33a41',
    authDomain: 'flutter-insta-33a41.firebaseapp.com',
    storageBucket: 'flutter-insta-33a41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnGuKti3VER1YbSrrzaz5hZvOXNv_Sbes',
    appId: '1:154524726030:android:d60ea735958b94a08add5f',
    messagingSenderId: '154524726030',
    projectId: 'flutter-insta-33a41',
    storageBucket: 'flutter-insta-33a41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UoqMKj10acKanBHs1tnsIA6pnayPDXE',
    appId: '1:154524726030:ios:9589b71fdeec25d18add5f',
    messagingSenderId: '154524726030',
    projectId: 'flutter-insta-33a41',
    storageBucket: 'flutter-insta-33a41.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UoqMKj10acKanBHs1tnsIA6pnayPDXE',
    appId: '1:154524726030:ios:9589b71fdeec25d18add5f',
    messagingSenderId: '154524726030',
    projectId: 'flutter-insta-33a41',
    storageBucket: 'flutter-insta-33a41.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9aF60c3G3czH6ZJCI9hY37gmu-72IgG8',
    appId: '1:154524726030:web:ba5b78c5630720ff8add5f',
    messagingSenderId: '154524726030',
    projectId: 'flutter-insta-33a41',
    authDomain: 'flutter-insta-33a41.firebaseapp.com',
    storageBucket: 'flutter-insta-33a41.appspot.com',
  );
}
